server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: payment-core

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payment_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: validate